version: "3.8"

services:
  db:
    image: ghcr.io/baosystems/postgis:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - config/dev.conf
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
      - 8888:8888
    depends_on:
      - db
    env_file:
      - config/dev.conf

volumes:
  postgres_data:
