# Generated by Django 3.0.7 on 2020-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_history'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favoriteorganization',
            constraint=models.UniqueConstraint(fields=('organization', 'person'), name='unique_favorite'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('organization', 'person'), name='unique_rating'),
        ),
    ]
