# Generated by Django 3.0.7 on 2020-07-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_auto_20200729_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
