# Generated by Django 3.0.7 on 2020-07-30 03:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_organization_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
