# Generated by Django 3.0.7 on 2020-07-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_organization_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ecommerce',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='facebook',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='twitter',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
