# Generated by Django 3.0.7 on 2020-08-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_auto_20200731_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
