# Generated by Django 3.0.7 on 2020-08-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_organization_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=None, upload_to='products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
