# Generated by Django 3.0.7 on 2020-08-05 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesses', '0010_auto_20200803_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgBrowsingHstry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_browsing_hstry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization_browsing_history',
            },
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
